# Generated by Django 3.2.9 on 2021-11-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrackerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
